apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-cicd
  template:
    metadata:
      labels:
        app: node-cicd
    spec:
      containers:
        - name: node-cicd
          image: kunal7045/node-cicd:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000